### ISSUE TITLE
This function has a return type of 'Widget', but doesn't end with a return statement. Try adding a return statement, or changing the return type to 'void'.dart(missing_return)

### ISSUE THREAD

**Issue by shivanandmn** [itsatifsiddiqui/providerLogin#1]
This function has a return type of 'Widget', but doesn't end with a return statement.
Try adding a return statement, or changing the return type to 'void'.dart(missing_return)
![image](https://user-images.githubusercontent.com/21271698/63667216-84774c00-c7f0-11e9-8cac-e84049afea85.png)

**Comment by anshulkataria4** [comment]
`builder: (context, UserRepository user, _) {
          switch (user.status) {
            case Status.Uninitialized:
              return Splash();
            case Status.Unauthenticated:
            case Status.Authenticating:
              return LoginPage();
            case Status.Authenticated:
              return UserInfoPage(user: user.user);
          }
          return null;
        },`

add null to resolve I guess

**Comment by anshulkataria4** [comment]
@itsatifsiddiqui  please resolve or I can create a branch and merge and add to this repo?

**Comment by itsatifsiddiqui** [comment]
Would be better ...

**Comment by theofficial-Shavar** [comment]
```dart
Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      builder: (_) => UserRepository.instance(),
      child: Consumer(
        builder: (context, UserRepository user, _) {
          switch (user.status) {
            case Status.Uninitialized:
              return Splash();
            case Status.Unauthenticated:
            case Status.Authenticating:
              return LoginPage();
            case Status.Authenticated:
              return UserInfoPage(user: user.user);
          }
          //Add return statement here.
          return LoginPage();
        },
      ),
    );
  }
```

**Comment by hanimhanna** [comment]
hi , when i run my app i get a red screen tells me ( RangeError (index): Invalid value: valid value range is empty: 0) 

the error i think is from this script

class SoccerApi {
  final String apiUrl = "https://v3.football.api-sports.io/fixtures?season=2020&league=39";
  static const headers = {'x-rapidapi-host': "v3.football.api-sports.io", 'x-rapidapi-key': "*************************"};

  Future<List<SoccerMatch>> getAllMatches() async {
    Response res = await get(apiUrl, headers: headers);
    var body;

    if (res.statusCode == 200) {
      body = jsonDecode(res.body);
      List<dynamic> matchesList = body['response'];
      print("Api service: $body");
      List<SoccerMatch> matches = matchesList.map((dynamic item) => SoccerMatch.fromJson(item)).toList();
      return matches;
    }
  }
}
 

can anyone solve this ??

**Comment by hanimhanna** [comment]
maybe the error from here i have to replace zero with something else ..

Widget pageBody (List<SoccerMatch> allmatches) {
  return Column(
    children: [
      Expanded(
        flex: 2,
        child: Container(
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 18.0, vertical: 24.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                teamStat("Local Team", allmatches[0].home.logoUrl,
                  allmatches[0].home.name),
                goalStat(allmatches[0].fixture.status.elapsedTime,
                  allmatches[0].goal.home, allmatches[0].goal.away),
                teamStat("Visitor Team", allmatches[0].away.logoUrl,
                  allmatches[0].away.name),
              ],
            ),
          ),
        ),
      ),

**Comment by hanimhanna** [comment]
oops it seems not for free to get the API key ..anyway thank you !!
