### ISSUE TITLE
Changes for the new provider package

### ISSUE THREAD

**Issue by marcmathys** [itsatifsiddiqui/providerLogin#4]
After changing builder to create.  This code gives an error message "This function has a return type 'Widget", but doesn't end with a return statement."

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => UserRepository.instance(),
      child: Consumer(
        builder: (context, UserRepository user, _) {
          switch (user.status) {
            case Status.Uninitialized:
              return Splash();
            case Status.Unauthenticated:
            case Status.Authenticating:
              return LoginPage();
            case Status.Authenticated:
              return UserInfoPage(user: user.user);
          }
        },
      ),
    );
  }
}

**Comment by itsatifsiddiqui** [comment]
you need to add the default case in the switch statement. 
return the LoginPage() in default.
